### ISSUE TITLE
Some problem about process_robotcar_images.py

### ISSUE THREAD

**Issue by NanakoSasaki** [NVlabs/geomapnet#24]
Dear Author:
    Sorry to bother. Because a lot of time need to be used in the training of RobotCar Full Scene using Nivida TITAN Xp (5 epoch per day), I try the the process_robotcar_images.py for hoping to speed up training. But, I got some unexpected problem while running the program.

/usr/bin/python2.7 /media/duanzd/local/experiment/1/GAL/geomapnet-master/scripts/process_robotcar_images.py --scene full
fatal: Not a git repository (or any of the parent directories): .git
  File "/media/duanzd/local/experiment/1/GAL/geomapnet-master/scripts/process_robotcar_images.py", line 38, in <module>
    transform = transforms.Compose([transforms.Scale(256),
/usr/local/lib/python2.7/dist-packages/torchvision/transforms/transforms.py:208: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
processing TRAIN data using 4 cores
Traceback (most recent call last):
  File "/media/duanzd/local/experiment/1/GAL/geomapnet-master/scripts/process_robotcar_images.py", line 71, in <module>
    for batch_idx, (imgs, _) in enumerate(loader):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/duanzd/local/experiment/1/GAL/geomapnet-master/dataset_loaders/robotcar.py", line 139, in __getitem__
    img = self.transform(img)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/transforms/transforms.py", line 195, in __call__
    return F.resize(img, self.size, self.interpolation)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/transforms/functional.py", line 229, in resize
    raise TypeError('img should be PIL Image. Got {}'.format(type(img)))
**TypeError: img should be PIL Image. Got <type 'numpy.ndarray'>**

Process finished with exit code 1

Does any one meets this problem?

Best wishes!

**Comment by samarth-robo** [comment]
`torchvision.transform` expects `PIL.Image`, not a numpy array. I pushed 9c0b3d064495a0e0ad7e5c8c18c62e1ca9008471 to fix this, can you verify it works now?

**Comment by NanakoSasaki** [comment]
Thank you for your reply! But it still doesn't work.

/usr/bin/python2.7 /media/duanzd/local/experiment/1/GAL/geomapnet-master/scripts/process_robotcar_images.py --scene full
fatal: Not a git repository (or any of the parent directories): .git
processing TRAIN data using 4 cores
  File "/media/duanzd/local/experiment/1/GAL/geomapnet-master/scripts/process_robotcar_images.py", line 38, in <module>
    transform = transforms.Compose([transforms.Scale(256),
/usr/local/lib/python2.7/dist-packages/torchvision/transforms/transforms.py:208: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Traceback (most recent call last):
  File "/media/duanzd/local/experiment/1/GAL/geomapnet-master/scripts/process_robotcar_images.py", line 67, in <module>
    for batch_idx, (imgs, _) in enumerate(loader):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/duanzd/local/experiment/1/GAL/geomapnet-master/dataset_loaders/robotcar.py", line 125, in __getitem__
    img = Image.fromarray(img)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2651, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type

I also have one question about the time and GPUs that your training RobotCar full scene is consumed. I use one TITAN Xp(12G) which is very slow. I hope to speed up the training using this process.

Best wishes!

**Comment by samarth-robo** [comment]
@NanakoSasaki hmm are you sure you are using [my fork](https://github.com/samarth-robo/robotcar-dataset-sdk) of the robotcar-sdk, as I mentioned in the README? In my fork, I've modified the `load_image` function to return a `PIL.Image`, which is what `transform` expects.
Now that I look at your original error, I think it might come from using some other version of the SDK. I'm reverting the commit 9c0b3d0, which was a false fix.
